print("There's a rhythm and rush these days")
print("Where the lights don't move and the colors don't fade")
print("Leaves you empty with nothing but dreams")
print("In a world gone shallow")
print("In a world gone lean")
print("Sometimes there's things a man connot know")
print("The gears won't turn and the leaves won't grow")
print("There's no place to run and no gasoline")
print("Engine won't turn and the train won't leave")